// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"sync"
	itemmodels "wish-list/internal/domain/item/models"
	wishlistmodels "wish-list/internal/domain/wishlist/models"
)

// Ensure, that WishListRepositoryInterfaceMock does implement WishListRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ WishListRepositoryInterface = &WishListRepositoryInterfaceMock{}

// WishListRepositoryInterfaceMock is a mock implementation of WishListRepositoryInterface.
//
//	func TestSomethingThatUsesWishListRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked WishListRepositoryInterface
//		mockedWishListRepositoryInterface := &WishListRepositoryInterfaceMock{
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*wishlistmodels.WishList, error) {
//				panic("mock out the GetByID method")
//			},
//		}
//
//		// use mockedWishListRepositoryInterface in code that requires WishListRepositoryInterface
//		// and then make assertions.
//
//	}
type WishListRepositoryInterfaceMock struct {
	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*wishlistmodels.WishList, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
	}
	lockGetByID sync.RWMutex
}

// GetByID calls GetByIDFunc.
func (mock *WishListRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*wishlistmodels.WishList, error) {
	if mock.GetByIDFunc == nil {
		panic("WishListRepositoryInterfaceMock.GetByIDFunc: method is nil but WishListRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedWishListRepositoryInterface.GetByIDCalls())
func (mock *WishListRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Ensure, that GiftItemRepositoryInterfaceMock does implement GiftItemRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ GiftItemRepositoryInterface = &GiftItemRepositoryInterfaceMock{}

// GiftItemRepositoryInterfaceMock is a mock implementation of GiftItemRepositoryInterface.
//
//	func TestSomethingThatUsesGiftItemRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked GiftItemRepositoryInterface
//		mockedGiftItemRepositoryInterface := &GiftItemRepositoryInterfaceMock{
//			CreateWithOwnerFunc: func(ctx context.Context, giftItem itemmodels.GiftItem) (*itemmodels.GiftItem, error) {
//				panic("mock out the CreateWithOwner method")
//			},
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*itemmodels.GiftItem, error) {
//				panic("mock out the GetByID method")
//			},
//			MarkManualReservationFunc: func(ctx context.Context, itemID pgtype.UUID, reservedByName string, note *string) (*itemmodels.GiftItem, error) {
//				panic("mock out the MarkManualReservation method")
//			},
//		}
//
//		// use mockedGiftItemRepositoryInterface in code that requires GiftItemRepositoryInterface
//		// and then make assertions.
//
//	}
type GiftItemRepositoryInterfaceMock struct {
	// CreateWithOwnerFunc mocks the CreateWithOwner method.
	CreateWithOwnerFunc func(ctx context.Context, giftItem itemmodels.GiftItem) (*itemmodels.GiftItem, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*itemmodels.GiftItem, error)

	// MarkManualReservationFunc mocks the MarkManualReservation method.
	MarkManualReservationFunc func(ctx context.Context, itemID pgtype.UUID, reservedByName string, note *string) (*itemmodels.GiftItem, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateWithOwner holds details about calls to the CreateWithOwner method.
		CreateWithOwner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GiftItem is the giftItem argument value.
			GiftItem itemmodels.GiftItem
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// MarkManualReservation holds details about calls to the MarkManualReservation method.
		MarkManualReservation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID pgtype.UUID
			// ReservedByName is the reservedByName argument value.
			ReservedByName string
			// Note is the note argument value.
			Note *string
		}
	}
	lockCreateWithOwner       sync.RWMutex
	lockGetByID               sync.RWMutex
	lockMarkManualReservation sync.RWMutex
}

// CreateWithOwner calls CreateWithOwnerFunc.
func (mock *GiftItemRepositoryInterfaceMock) CreateWithOwner(ctx context.Context, giftItem itemmodels.GiftItem) (*itemmodels.GiftItem, error) {
	if mock.CreateWithOwnerFunc == nil {
		panic("GiftItemRepositoryInterfaceMock.CreateWithOwnerFunc: method is nil but GiftItemRepositoryInterface.CreateWithOwner was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		GiftItem itemmodels.GiftItem
	}{
		Ctx:      ctx,
		GiftItem: giftItem,
	}
	mock.lockCreateWithOwner.Lock()
	mock.calls.CreateWithOwner = append(mock.calls.CreateWithOwner, callInfo)
	mock.lockCreateWithOwner.Unlock()
	return mock.CreateWithOwnerFunc(ctx, giftItem)
}

// CreateWithOwnerCalls gets all the calls that were made to CreateWithOwner.
// Check the length with:
//
//	len(mockedGiftItemRepositoryInterface.CreateWithOwnerCalls())
func (mock *GiftItemRepositoryInterfaceMock) CreateWithOwnerCalls() []struct {
	Ctx      context.Context
	GiftItem itemmodels.GiftItem
} {
	var calls []struct {
		Ctx      context.Context
		GiftItem itemmodels.GiftItem
	}
	mock.lockCreateWithOwner.RLock()
	calls = mock.calls.CreateWithOwner
	mock.lockCreateWithOwner.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *GiftItemRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*itemmodels.GiftItem, error) {
	if mock.GetByIDFunc == nil {
		panic("GiftItemRepositoryInterfaceMock.GetByIDFunc: method is nil but GiftItemRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedGiftItemRepositoryInterface.GetByIDCalls())
func (mock *GiftItemRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// MarkManualReservation calls MarkManualReservationFunc.
func (mock *GiftItemRepositoryInterfaceMock) MarkManualReservation(ctx context.Context, itemID pgtype.UUID, reservedByName string, note *string) (*itemmodels.GiftItem, error) {
	if mock.MarkManualReservationFunc == nil {
		panic("GiftItemRepositoryInterfaceMock.MarkManualReservationFunc: method is nil but GiftItemRepositoryInterface.MarkManualReservation was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ItemID         pgtype.UUID
		ReservedByName string
		Note           *string
	}{
		Ctx:            ctx,
		ItemID:         itemID,
		ReservedByName: reservedByName,
		Note:           note,
	}
	mock.lockMarkManualReservation.Lock()
	mock.calls.MarkManualReservation = append(mock.calls.MarkManualReservation, callInfo)
	mock.lockMarkManualReservation.Unlock()
	return mock.MarkManualReservationFunc(ctx, itemID, reservedByName, note)
}

// MarkManualReservationCalls gets all the calls that were made to MarkManualReservation.
func (mock *GiftItemRepositoryInterfaceMock) MarkManualReservationCalls() []struct {
	Ctx            context.Context
	ItemID         pgtype.UUID
	ReservedByName string
	Note           *string
} {
	var calls []struct {
		Ctx            context.Context
		ItemID         pgtype.UUID
		ReservedByName string
		Note           *string
	}
	mock.lockMarkManualReservation.RLock()
	calls = mock.calls.MarkManualReservation
	mock.lockMarkManualReservation.RUnlock()
	return calls
}
