// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"sync"
	"wish-list/internal/domain/item/models"
	"wish-list/internal/domain/item/repository"
)

// Ensure, that GiftItemPurchaseRepositoryInterfaceMock does implement repository.GiftItemPurchaseRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ repository.GiftItemPurchaseRepositoryInterface = &GiftItemPurchaseRepositoryInterfaceMock{}

// GiftItemPurchaseRepositoryInterfaceMock is a mock implementation of repository.GiftItemPurchaseRepositoryInterface.
//
//	func TestSomethingThatUsesGiftItemPurchaseRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked repository.GiftItemPurchaseRepositoryInterface
//		mockedGiftItemPurchaseRepositoryInterface := &GiftItemPurchaseRepositoryInterfaceMock{
//			MarkAsPurchasedFunc: func(ctx context.Context, giftItemID pgtype.UUID, userID pgtype.UUID, purchasedPrice pgtype.Numeric) (*models.GiftItem, error) {
//				panic("mock out the MarkAsPurchased method")
//			},
//		}
//
//		// use mockedGiftItemPurchaseRepositoryInterface in code that requires repository.GiftItemPurchaseRepositoryInterface
//		// and then make assertions.
//
//	}
type GiftItemPurchaseRepositoryInterfaceMock struct {
	// MarkAsPurchasedFunc mocks the MarkAsPurchased method.
	MarkAsPurchasedFunc func(ctx context.Context, giftItemID pgtype.UUID, userID pgtype.UUID, purchasedPrice pgtype.Numeric) (*models.GiftItem, error)

	// calls tracks calls to the methods.
	calls struct {
		// MarkAsPurchased holds details about calls to the MarkAsPurchased method.
		MarkAsPurchased []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GiftItemID is the giftItemID argument value.
			GiftItemID pgtype.UUID
			// UserID is the userID argument value.
			UserID pgtype.UUID
			// PurchasedPrice is the purchasedPrice argument value.
			PurchasedPrice pgtype.Numeric
		}
	}
	lockMarkAsPurchased sync.RWMutex
}

// MarkAsPurchased calls MarkAsPurchasedFunc.
func (mock *GiftItemPurchaseRepositoryInterfaceMock) MarkAsPurchased(ctx context.Context, giftItemID pgtype.UUID, userID pgtype.UUID, purchasedPrice pgtype.Numeric) (*models.GiftItem, error) {
	if mock.MarkAsPurchasedFunc == nil {
		panic("GiftItemPurchaseRepositoryInterfaceMock.MarkAsPurchasedFunc: method is nil but GiftItemPurchaseRepositoryInterface.MarkAsPurchased was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		GiftItemID     pgtype.UUID
		UserID         pgtype.UUID
		PurchasedPrice pgtype.Numeric
	}{
		Ctx:            ctx,
		GiftItemID:     giftItemID,
		UserID:         userID,
		PurchasedPrice: purchasedPrice,
	}
	mock.lockMarkAsPurchased.Lock()
	mock.calls.MarkAsPurchased = append(mock.calls.MarkAsPurchased, callInfo)
	mock.lockMarkAsPurchased.Unlock()
	return mock.MarkAsPurchasedFunc(ctx, giftItemID, userID, purchasedPrice)
}

// MarkAsPurchasedCalls gets all the calls that were made to MarkAsPurchased.
// Check the length with:
//
//	len(mockedGiftItemPurchaseRepositoryInterface.MarkAsPurchasedCalls())
func (mock *GiftItemPurchaseRepositoryInterfaceMock) MarkAsPurchasedCalls() []struct {
	Ctx            context.Context
	GiftItemID     pgtype.UUID
	UserID         pgtype.UUID
	PurchasedPrice pgtype.Numeric
} {
	var calls []struct {
		Ctx            context.Context
		GiftItemID     pgtype.UUID
		UserID         pgtype.UUID
		PurchasedPrice pgtype.Numeric
	}
	mock.lockMarkAsPurchased.RLock()
	calls = mock.calls.MarkAsPurchased
	mock.lockMarkAsPurchased.RUnlock()
	return calls
}
