// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"sync"
	"time"
	"wish-list/internal/repositories"
	db "wish-list/internal/shared/db/models"
)

// Ensure, that UserRepositoryInterfaceMock does implement repositories.UserRepositoryInterface.
// If this is not the case, regenerate this file with moq.
var _ repositories.UserRepositoryInterface = &UserRepositoryInterfaceMock{}

// UserRepositoryInterfaceMock is a mock implementation of repositories.UserRepositoryInterface.
//
//	func TestSomethingThatUsesUserRepositoryInterface(t *testing.T) {
//
//		// make and configure a mocked repositories.UserRepositoryInterface
//		mockedUserRepositoryInterface := &UserRepositoryInterfaceMock{
//			CreateFunc: func(ctx context.Context, user db.User) (*db.User, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id pgtype.UUID) error {
//				panic("mock out the Delete method")
//			},
//			DeleteWithExecutorFunc: func(ctx context.Context, executor db.Executor, id pgtype.UUID) error {
//				panic("mock out the DeleteWithExecutor method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*db.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(ctx context.Context, id pgtype.UUID) (*db.User, error) {
//				panic("mock out the GetByID method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*db.User, error) {
//				panic("mock out the List method")
//			},
//			ListInactiveSinceFunc: func(ctx context.Context, since time.Time) ([]*db.User, error) {
//				panic("mock out the ListInactiveSince method")
//			},
//			UpdateFunc: func(ctx context.Context, user db.User) (*db.User, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepositoryInterface in code that requires repositories.UserRepositoryInterface
//		// and then make assertions.
//
//	}
type UserRepositoryInterfaceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user db.User) (*db.User, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id pgtype.UUID) error

	// DeleteWithExecutorFunc mocks the DeleteWithExecutor method.
	DeleteWithExecutorFunc func(ctx context.Context, executor db.Executor, id pgtype.UUID) error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*db.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id pgtype.UUID) (*db.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*db.User, error)

	// ListInactiveSinceFunc mocks the ListInactiveSince method.
	ListInactiveSinceFunc func(ctx context.Context, since time.Time) ([]*db.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user db.User) (*db.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User db.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// DeleteWithExecutor holds details about calls to the DeleteWithExecutor method.
		DeleteWithExecutor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Executor is the executor argument value.
			Executor db.Executor
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListInactiveSince holds details about calls to the ListInactiveSince method.
		ListInactiveSince []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Since is the since argument value.
			Since time.Time
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User db.User
		}
	}
	lockCreate             sync.RWMutex
	lockDelete             sync.RWMutex
	lockDeleteWithExecutor sync.RWMutex
	lockGetByEmail         sync.RWMutex
	lockGetByID            sync.RWMutex
	lockList               sync.RWMutex
	lockListInactiveSince  sync.RWMutex
	lockUpdate             sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepositoryInterfaceMock) Create(ctx context.Context, user db.User) (*db.User, error) {
	if mock.CreateFunc == nil {
		panic("UserRepositoryInterfaceMock.CreateFunc: method is nil but UserRepositoryInterface.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User db.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.CreateCalls())
func (mock *UserRepositoryInterfaceMock) CreateCalls() []struct {
	Ctx  context.Context
	User db.User
} {
	var calls []struct {
		Ctx  context.Context
		User db.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryInterfaceMock) Delete(ctx context.Context, id pgtype.UUID) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryInterfaceMock.DeleteFunc: method is nil but UserRepositoryInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.DeleteCalls())
func (mock *UserRepositoryInterfaceMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteWithExecutor calls DeleteWithExecutorFunc.
func (mock *UserRepositoryInterfaceMock) DeleteWithExecutor(ctx context.Context, executor db.Executor, id pgtype.UUID) error {
	if mock.DeleteWithExecutorFunc == nil {
		panic("UserRepositoryInterfaceMock.DeleteWithExecutorFunc: method is nil but UserRepositoryInterface.DeleteWithExecutor was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Executor db.Executor
		ID       pgtype.UUID
	}{
		Ctx:      ctx,
		Executor: executor,
		ID:       id,
	}
	mock.lockDeleteWithExecutor.Lock()
	mock.calls.DeleteWithExecutor = append(mock.calls.DeleteWithExecutor, callInfo)
	mock.lockDeleteWithExecutor.Unlock()
	return mock.DeleteWithExecutorFunc(ctx, executor, id)
}

// DeleteWithExecutorCalls gets all the calls that were made to DeleteWithExecutor.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.DeleteWithExecutorCalls())
func (mock *UserRepositoryInterfaceMock) DeleteWithExecutorCalls() []struct {
	Ctx      context.Context
	Executor db.Executor
	ID       pgtype.UUID
} {
	var calls []struct {
		Ctx      context.Context
		Executor db.Executor
		ID       pgtype.UUID
	}
	mock.lockDeleteWithExecutor.RLock()
	calls = mock.calls.DeleteWithExecutor
	mock.lockDeleteWithExecutor.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepositoryInterfaceMock) GetByEmail(ctx context.Context, email string) (*db.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepositoryInterfaceMock.GetByEmailFunc: method is nil but UserRepositoryInterface.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.GetByEmailCalls())
func (mock *UserRepositoryInterfaceMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserRepositoryInterfaceMock) GetByID(ctx context.Context, id pgtype.UUID) (*db.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserRepositoryInterfaceMock.GetByIDFunc: method is nil but UserRepositoryInterface.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.GetByIDCalls())
func (mock *UserRepositoryInterfaceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepositoryInterfaceMock) List(ctx context.Context, limit int, offset int) ([]*db.User, error) {
	if mock.ListFunc == nil {
		panic("UserRepositoryInterfaceMock.ListFunc: method is nil but UserRepositoryInterface.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.ListCalls())
func (mock *UserRepositoryInterfaceMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListInactiveSince calls ListInactiveSinceFunc.
func (mock *UserRepositoryInterfaceMock) ListInactiveSince(ctx context.Context, since time.Time) ([]*db.User, error) {
	if mock.ListInactiveSinceFunc == nil {
		panic("UserRepositoryInterfaceMock.ListInactiveSinceFunc: method is nil but UserRepositoryInterface.ListInactiveSince was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Since time.Time
	}{
		Ctx:   ctx,
		Since: since,
	}
	mock.lockListInactiveSince.Lock()
	mock.calls.ListInactiveSince = append(mock.calls.ListInactiveSince, callInfo)
	mock.lockListInactiveSince.Unlock()
	return mock.ListInactiveSinceFunc(ctx, since)
}

// ListInactiveSinceCalls gets all the calls that were made to ListInactiveSince.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.ListInactiveSinceCalls())
func (mock *UserRepositoryInterfaceMock) ListInactiveSinceCalls() []struct {
	Ctx   context.Context
	Since time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Since time.Time
	}
	mock.lockListInactiveSince.RLock()
	calls = mock.calls.ListInactiveSince
	mock.lockListInactiveSince.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryInterfaceMock) Update(ctx context.Context, user db.User) (*db.User, error) {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryInterfaceMock.UpdateFunc: method is nil but UserRepositoryInterface.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User db.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepositoryInterface.UpdateCalls())
func (mock *UserRepositoryInterfaceMock) UpdateCalls() []struct {
	Ctx  context.Context
	User db.User
} {
	var calls []struct {
		Ctx  context.Context
		User db.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
